# Generated by Django 3.0.2 on 2020-01-16 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VisitedPage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_visit', models.DateTimeField(auto_now=True)),
                ('keyword', models.CharField(max_length=200)),
                ('page_url', models.URLField()),
                ('domain', models.CharField(max_length=200)),
                ('load_time', models.PositiveIntegerField()),
                ('response_type', models.PositiveIntegerField()),
                ('page_size', models.PositiveIntegerField()),
            ],
            options={
                'ordering': ('date_of_visit',),
            },
        ),
    ]
