const FETCH_VISITED_PAGES = 'FETCH_VISITED_PAGES';
const FETCH_KEYWORDS = 'FETCH_KEYWORDS';
const FETCH_DOMAINS = 'FETCH_DOMAINS';
const SET_FROM_DATE = 'SET_FROM_DATE';
const SET_UNTIL_DATE = 'SET_UNTIL_DATE';
const SET_KEYWORD = 'SET_KEYWORD';
const SET_DOMAIN = 'SET_DOMAIN';
const SET_STATUS_CODE = 'SET_STATUS_CODE';
const SET_MIN_PAGE_SIZE = 'SET_MIN_PAGE_SIZE';
const SET_DATE_GROUPING = 'SET_DATE_GROUPING';
const RESET_DATE_GROUPING = 'RESET_DATE_GROUPING';
const SET_KEYWORD_GROUPING = 'SET_KEYWORD_GROUPING';
const RESET_KEYWORD_GROUPING = 'RESET_KEYWORD_GROUPING';
const SET_DOMAIN_GROUPING = 'SET_DOMAIN_GROUPING';
const RESET_DOMAIN_GROUPING = 'RESET_DOMAIN_GROUPING';
const SET_STATUS_CODE_GROUPING = 'SET_STATUS_CODE_GROUPING';
const RESET_STATUS_CODE_GROUPING = 'RESET_STATUS_CODE_GROUPING';
const CLEAR_STATE = 'CLEAR_STATE';
const DISABLE_CLEAR_BUTTON = 'DISABLE_CLEAR_BUTTON';

export default {
  FETCH_VISITED_PAGES,
  FETCH_KEYWORDS,
  FETCH_DOMAINS,
  SET_FROM_DATE,
  SET_UNTIL_DATE,
  SET_KEYWORD,
  SET_DOMAIN,
  SET_STATUS_CODE,
  SET_MIN_PAGE_SIZE,
  SET_DATE_GROUPING,
  RESET_DATE_GROUPING,
  SET_KEYWORD_GROUPING,
  RESET_KEYWORD_GROUPING,
  SET_DOMAIN_GROUPING,
  RESET_DOMAIN_GROUPING,
  SET_STATUS_CODE_GROUPING,
  RESET_STATUS_CODE_GROUPING,
  CLEAR_STATE,
  DISABLE_CLEAR_BUTTON,
}